#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serieapi.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SERIESTV")]
	public partial class SerieTvDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    #endregion
		
		public SerieTvDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SERIESTVConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SerieTvDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SerieTvDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SerieTvDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SerieTvDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.jf_sp_search_serie_by_name")]
		public ISingleResult<jf_sp_search_serie_by_nameResult> jf_sp_search_serie_by_name([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(256)")] string serie_nom)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), serie_nom);
			return ((ISingleResult<jf_sp_search_serie_by_nameResult>)(result.ReturnValue));
		}
	}
	
	public partial class jf_sp_search_serie_by_nameResult
	{
		
		private int _serie_id;
		
		private string _serie_nom;
		
		private int _serie_an;
		
		private int _disque_id;
		
		public jf_sp_search_serie_by_nameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serie_id", DbType="Int NOT NULL")]
		public int serie_id
		{
			get
			{
				return this._serie_id;
			}
			set
			{
				if ((this._serie_id != value))
				{
					this._serie_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serie_nom", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string serie_nom
		{
			get
			{
				return this._serie_nom;
			}
			set
			{
				if ((this._serie_nom != value))
				{
					this._serie_nom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serie_an", DbType="Int NOT NULL")]
		public int serie_an
		{
			get
			{
				return this._serie_an;
			}
			set
			{
				if ((this._serie_an != value))
				{
					this._serie_an = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_disque_id", DbType="Int NOT NULL")]
		public int disque_id
		{
			get
			{
				return this._disque_id;
			}
			set
			{
				if ((this._disque_id != value))
				{
					this._disque_id = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
